# Importa a Numpy

In [1]:
import numpy as np

# Consulta a versão e caminho para arquivos

In [2]:
print(np.__version__)

1.19.2


In [3]:
print(np.__path__)
# np.__spec__
# np.__doc__

['C:\\Users\\berna\\anaconda3\\lib\\site-packages\\numpy']


# Conteúdo carregado

In [4]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [5]:
from timeit import default_timer as tmr

l = list(range(100000000))
v = np.array(l)

i = tmr(); sum(l);  e = tmr(); a = e - i; a
i = tmr(); v.sum(); e = tmr(); b = e - i; b
a/b

u = 999
i = tmr(); y = [x * u for x in l]; e = tmr(); a = e - i; a
i = tmr(); f = v * u; e = tmr(); b = e - i; b
a/b

u = 100000
i = tmr(); f = [x for x in l if x > u]; e = tmr(); a = e - i; a
i = tmr(); f = v[v > u]; e = tmr(); b = e - i; b
a/b

11.850010558821037

In [6]:
i = tmr(); sum(l);  e = tmr(); a = e - i; a

4.4278853

In [7]:
i = tmr(); v.sum(); e = tmr(); b = e - i; b

0.10842720000000838

In [8]:
a/b

40.837403345282894

In [9]:
u = 999
i = tmr(); y = [x * u for x in l]; e = tmr(); a = e - i; a

25.033557799999997

In [10]:
i = tmr(); f = v * u; e = tmr(); b = e - i; b

0.6997917999999856

In [11]:
a/b

35.77286530079448

In [12]:
u = 100000
i = tmr(); f = [x for x in l if x > u]; e = tmr(); a = e - i; a

14.24935050000002

In [13]:
i = tmr(); f = v[v > u]; e = tmr(); b = e - i; b

1.2361564000000271

In [14]:
a/b

11.527142115673799

In [15]:
# Um array unidimensional.
A = np.array([4, 7, 5, 1, 9, 7, 4, 0]); A

array([4, 7, 5, 1, 9, 7, 4, 0])

In [16]:
# Modifica as dimensões para redispor o conteúdo.
A.shape = (2, 4); A

array([[4, 7, 5, 1],
       [9, 7, 4, 0]])

In [17]:
# Um array tridimensional.
A.shape = (2, 2, 2); A

array([[[4, 7],
        [5, 1]],

       [[9, 7],
        [4, 0]]])

In [18]:
# Vetor de 0.
np.zeros(shape = 4)

array([0., 0., 0., 0.])

In [19]:
# Vetor de 1.
np.ones(shape = 4)

array([1., 1., 1., 1.])

In [20]:
# Vetor vazio (nan).
np.empty(shape = 4)

array([1., 1., 1., 1.])

In [21]:
# Vetor de algo qualquer.
np.full(shape = 4, fill_value = 99)

array([99, 99, 99, 99])

In [22]:
# Sequências regulares.
np.arange(start = 0, stop = 12, step = 2)

array([ 0,  2,  4,  6,  8, 10])

In [23]:
np.linspace(start = 0, stop = 12, num = 7)

array([ 0.,  2.,  4.,  6.,  8., 10., 12.])

In [24]:
np.logspace(start = -3, stop = 3, num = 7, base = 2)

array([0.125, 0.25 , 0.5  , 1.   , 2.   , 4.   , 8.   ])

In [25]:
np.geomspace(start = 2**(-3), stop = 2**3, num = 7)

array([0.125, 0.25 , 0.5  , 1.   , 2.   , 4.   , 8.   ])

# Repetições

In [26]:
np.repeat(a = np.array([1, 2, 3]), repeats = 2)

array([1, 1, 2, 2, 3, 3])

In [27]:
np.repeat(a = np.array([[1, 2], [3, 4]]), repeats = 2, axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [28]:
np.repeat(a = np.array([[1, 2], [3, 4]]), repeats = 2, axis = 1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [29]:
np.repeat(a = np.array([[1, 2], [3, 4]]), repeats = [2, 1], axis = 0)

array([[1, 2],
       [1, 2],
       [3, 4]])

In [30]:
# Isso pode ser obtido com soma direta ou Kronecker.
np.tile(A = [1, 2, 3], reps = 2)

array([1, 2, 3, 1, 2, 3])

In [31]:
np.tile(A = [1, 2, 3], reps = [3, 2])

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [32]:
np.tile(A = np.array([[1, 2], [3, 4]]), reps = [3, 2])

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

# Vetores com números aleatórios

In [33]:
# Números da distribuição uniforme contínua.
np.random.random(size = 3)

array([0.01020888, 0.89864382, 0.96522195])

In [34]:
np.random.uniform(low = 0, high = 1, size = 4)

array([9.01216021e-01, 6.93461680e-01, 8.84280731e-02, 3.31716010e-04])

In [35]:
# Números da distribuição uniforme discreta.
np.random.randint(low = 0, high = 10, size = 20)

array([0, 6, 1, 4, 6, 1, 9, 6, 4, 1, 6, 5, 7, 2, 5, 2, 3, 6, 9, 6])

In [36]:
# Amostragem de um vetor de valores.
np.random.choice(a = [100, 200, 300], size = 7, replace = True)

array([200, 300, 200, 300, 100, 300, 100])

In [37]:
# Números da distribuição normal.
np.random.normal(loc = 0, scale = 1, size = 4)

array([0.27159443, 0.79627314, 0.68970777, 0.20667024])

# Matrizes com números aleatórios

In [38]:
# Arrays multimensionais da uniforme contínua e normal padrão.
np.random.rand(3, 4)

array([[0.06540485, 0.3844377 , 0.96032503, 0.42771291],
       [0.28745645, 0.81846948, 0.66193744, 0.62741565],
       [0.80081745, 0.81903164, 0.21292552, 0.49368107]])

In [39]:
np.random.randn(3, 4)

array([[-0.81716574, -0.73036887, -0.06689688,  0.51820489],
       [-0.89360189,  0.20710909, -0.53230234,  1.50067175],
       [-1.05593896,  1.23767732,  1.1575523 ,  1.04429362]])

# Seleção em arrays

In [40]:
# Uma sequência regular.
A = np.linspace(start = 100, stop = 110, num = 11); A

array([100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.])

In [41]:
# Fatiamentos.
A[0:2]    # Do 0 até 1 inclusive.

array([100., 101.])

In [42]:
A[:2]     # Idem.

array([100., 101.])

In [43]:
A[2:]     # Do 2 até o final.

array([102., 103., 104., 105., 106., 107., 108., 109., 110.])

In [44]:
A[-2:]    # Do 2 de trás para frente até o final.

array([109., 110.])

In [45]:
A[::2]    # Do começo ao final com passo 2.

array([100., 102., 104., 106., 108., 110.])

In [46]:
# Conjuntos.
A[[1, 5, 9]]  # Na posição 1, 5 e 9.

array([101., 105., 109.])

In [47]:
A[[1, -5, 9]] # Nas posição 1, 5 vindo do final e 9.

array([101., 106., 109.])

In [48]:
A = np.random.rand(3, 4)
A

array([[0.2573258 , 0.20528566, 0.31990542, 0.9063592 ],
       [0.2814863 , 0.87890895, 0.41882107, 0.56318612],
       [0.42804235, 0.25134086, 0.83021599, 0.33971873]])

In [49]:
A[0, :]      # Linha 0 e todas as colunas.

array([0.2573258 , 0.20528566, 0.31990542, 0.9063592 ])

In [50]:
A[0:2, :]    # Linha 0 e 1 e todas as colunas.

array([[0.2573258 , 0.20528566, 0.31990542, 0.9063592 ],
       [0.2814863 , 0.87890895, 0.41882107, 0.56318612]])

In [51]:
A[:, 0:3]    # Todas as linhas e colunas até 2.

array([[0.2573258 , 0.20528566, 0.31990542],
       [0.2814863 , 0.87890895, 0.41882107],
       [0.42804235, 0.25134086, 0.83021599]])

In [52]:
A[0:2, 0:3]  # Junção das anteriores.

array([[0.2573258 , 0.20528566, 0.31990542],
       [0.2814863 , 0.87890895, 0.41882107]])

# Operadores de comparação

In [53]:
A = np.random.randint(low = 1, high = 5, size = 20); A

array([3, 3, 1, 2, 2, 2, 4, 4, 3, 4, 2, 2, 1, 1, 1, 3, 1, 1, 1, 4])

In [54]:
A[A > 3]  # Maior.

array([4, 4, 4, 4])

In [55]:
A[A >= 3] # Maior ou igual.

array([3, 3, 4, 4, 3, 4, 3, 4])

In [56]:
A[A < 3]  # Menor.

array([1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1])

In [57]:
A[A <= 3] # Menor ou igual

array([3, 3, 1, 2, 2, 2, 3, 2, 2, 1, 1, 1, 3, 1, 1, 1])

In [58]:
A[A == 3] # Igual

array([3, 3, 3, 3])

In [59]:
A[A != 3] # Diferente.

array([1, 2, 2, 2, 4, 4, 4, 2, 2, 1, 1, 1, 1, 1, 1, 4])

# Operadores lógicos

In [60]:
A[(A > 8) & (A < 12)]  # Operador AND.

array([], dtype=int32)

In [61]:
A[(A < 8) | (A > 12)]  # Operador OR.

array([3, 3, 1, 2, 2, 2, 4, 4, 3, 4, 2, 2, 1, 1, 1, 3, 1, 1, 1, 4])

In [62]:
A[~(A == 3)]           # Operador NOT.

array([1, 2, 2, 2, 4, 4, 4, 2, 2, 1, 1, 1, 1, 1, 1, 4])

# Principais operações matriciais

In [68]:
A = np.random.rand(3, 4);A

array([[0.50974875, 0.43836429, 0.46309821, 0.12089953],
       [0.73563519, 0.52736437, 0.87961062, 0.41049888],
       [0.78720056, 0.03831795, 0.25551994, 0.44955572]])

In [69]:
B = np.random.rand(4, 5);B

array([[0.90244792, 0.42509692, 0.55531119, 0.20248038, 0.00379676],
       [0.27039732, 0.0635976 , 0.86421404, 0.16857541, 0.18969275],
       [0.03969789, 0.90685256, 0.17982571, 0.37670519, 0.29819411],
       [0.1635487 , 0.22798774, 0.53120856, 0.36973403, 0.25798553]])

In [70]:
C = np.random.rand(3, 3);C

array([[0.92656105, 0.88756874, 0.62805265],
       [0.84553283, 0.78734599, 0.50119766],
       [0.00917014, 0.55386623, 0.56540004]])

In [71]:
D = np.random.rand(4, 4);D

array([[0.50361927, 0.49488541, 0.96081289, 0.33416398],
       [0.95821449, 0.94515391, 0.24747622, 0.90894399],
       [0.62363317, 0.89160984, 0.68708674, 0.63673715],
       [0.11524595, 0.67790178, 0.19179507, 0.68708653]])

In [74]:
A + A

array([[1.01949749, 0.87672858, 0.92619643, 0.24179907],
       [1.47127038, 1.05472875, 1.75922123, 0.82099776],
       [1.57440112, 0.07663591, 0.51103989, 0.89911144]])

In [75]:
C - C

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [76]:
D * D

array([[0.25363237, 0.24491157, 0.92316141, 0.11166556],
       [0.91817502, 0.89331591, 0.06124448, 0.82617918],
       [0.38891832, 0.7949681 , 0.47208818, 0.4054342 ],
       [0.01328163, 0.45955082, 0.03678535, 0.4720879 ]])

In [77]:
D / D

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
# Produto matricial.
A.dot(B)

array([[0.61671121, 0.69209695, 0.8094096 , 0.39626373, 0.25437341],
       [0.90852561, 1.23752122, 1.24049928, 0.72098165, 0.4710277 ],
       [0.80443644, 0.67128557, 0.7550131 , 0.42832387, 0.20243086]])

In [79]:
C.dot(A)

array([[1.61964352, 0.8983091 , 1.37028363, 0.75871143],
       [1.40475179, 0.80507449, 1.21218863, 0.65074544],
       [0.85720119, 0.31777415, 0.63590427, 0.48264896]])

In [80]:
A.T              # Transposta.

array([[0.50974875, 0.73563519, 0.78720056],
       [0.43836429, 0.52736437, 0.03831795],
       [0.46309821, 0.87961062, 0.25551994],
       [0.12089953, 0.41049888, 0.44955572]])

In [81]:
np.diag(C)       # Diagonal.

array([0.92656105, 0.78734599, 0.56540004])

In [82]:
np.linalg.inv(C) # Inversa.

array([[  6.80694771,  -6.2547052 ,  -2.01676307],
       [-19.23311369,  21.04687844,   2.70739591],
       [ 18.73036904, -20.51609083,  -0.8507979 ]])

In [83]:
np.linalg.det(C) # Determinante.

0.02461734789532993

# Operações aritméticas e estatísticas

In [84]:
A = np.random.normal(loc = 10, scale = 1.5, size = 50)
[A.sum(), A.mean(), A.var(),
 A.std(), A.max(),  A.min()]

[504.10334049736525,
 10.082066809947305,
 3.308073549732672,
 1.818811026394076,
 13.447441393066144,
 4.712439556446617]

In [87]:
np.mean(a = A)

10.082066809947305

In [88]:
np.median(a = A)

10.133106793074528

In [89]:
np.quantile(a = A, q = [0.25, 0.75])

array([ 9.14805731, 11.18046251])

In [90]:
B = np.random.rand(3, 4)
np.mean(a = B)

0.3764746330360651

In [91]:
np.mean(a = B, axis = 0)

array([0.48866702, 0.34452985, 0.43370213, 0.23899952])

In [92]:
np.mean(a = B, axis = 1)

array([0.32267707, 0.31936629, 0.48738054])